### PR TITLE
Handle case of 9 byte unsigned 64bit integers with leading 0 byte

### PR DESCRIPTION
**Pull request by gavinaiken**
Came across an SNMP agent producing 9 byte uint64's today, this pull request handles that case following the model of the `readUint` function by dropping the first byte if it is zero.

### CODE REVIEW

**Comment by gavinaiken** [comment]
@stephenwvickers do you accept PRs to this code? Do I need to sign any contributor agreements or anything like that?

**Comment by stephenwvickers** [comment]
Hi Gavin,

Patch requests are welcome, no need to sign anything.

I need to spend a little time looking into this, I want to see how the asn1 module handles this case, if at all.

Steve

**Comment by gavinaiken** [comment]
Ah ok, thanks. I didn't check into what asn1 does with `long`s, sorry, should have done that first myself.

**Comment by gavinaiken** [comment]
So how does it look @stephenwvickers ? Wondering whether to use my fork in my app for a while, or if you might get my change (or something with the same effect) released soon?

**Comment by gavinaiken** [comment]
Hi Steve, any progress with reviewing this PR for inclusion in the library?

**Comment by stephenwvickers** [comment]
No, unfortunately not.  I will most likely get time to do so next week.

**Comment by stephenwvickers** [comment]
Hi @gavinaiken,

Having reviewed the code I think the change required is actually quite simple.  We will simply drop the 8 byte check:

```javascript
	if (value.length > 8)
  		throw new RequestInvalidError ("64 bit unsigned integer too long '"
  				+ value.length + "'");
```

We produce a Buffer object so there's no need to perform this check in our code.

I will reject the pull request and make the change.

Steve

**Comment by gavinaiken** [comment]
Sounds good, thanks!

**Pull request closed without merging**
